# Site settings
title: Olive Power
twitter_username: opowero
name: Olive Power

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: Blog
   url: https://www.thekubehow.com/
 - title: GitHub
   url: https://github.com/opowbow
 - title: KubeAcademy
   url: https://kube.academy/instructors
 - title: Podlets
   url: https://thepodlets.io/
 - title: LinkedIn
   url: https://www.linkedin.com/in/olive-power-488870138/

#Any buzzword skills you want to include
skills:
 - Kubernetes
 - Heptio
 - Microservices
 - Tanzu
 - Radia
 - Enterprise Management
 - Go
 - Cloudforms
 - ansible
 - kubebuilder
 - infrastructure
 - containers
 - CKA
 - technical architecture
 - education

#Blogfeed is optional - including this will add JS to call the feed and populate blog list
#blogfeed: https://automateddeveloper.blogspot.com/feeds/posts/default?alt=json

#Work experience is required
roles:
 - title: Staff Systems Engineer
   start: 2019
   end: Ongoing
   employer: VMware
   description: The Emerging techonolgy team within VMWare is always at the forefront of direction and strategy. <br/> As part of this team, I am involved in many aspects including leading technical discussions and presentations for the sales organization during key sales interactions; Strategic solution design for cloud native technologies and bringing the possibilities alive for the customers; Enabling sales and the wider VMware team in emerging technologies through training, demos and writeups; Testing and reviewing specific kubernetes projects internally – including cAPZ and cAPV;  Product team engagement to drive product direction and roadmap from direct feedback from customer interaction and requirements; Kubernetes and realated products at VMware include those listed here <a href="https://tanzu.vmware.com/tanzu" taget="_blank">VMware Tanzu</a>.
 - title: Field Engineer
   start: 2018
   end: 2019
   employer: Heptio
   description: At Heptio we built an impactful and significant global Kubernetes startup - with a significant community following, delivering consultancy and services in the CNCF technology space.<br/> Heptio was successfully acquired by VMware in 2018. <br/> Engagements for Heptio included lots of things (being a startup) including - First on the ground engineer helping to build net new business in the UK and broader EMEA regions; Design of custom, bespoke open source-based solutions for Kubernetes platforms for medium and largescale organisations – framed by education, requirement discovery, solution investigation and best practices for security and design - with scale in mind;  Customer enablement around Kubernetes and DevOps technologies and best practice;  Delivery of service engagements for customer – technical assessments, project delivery and technical support of kubernetes based implementations;  Evangelist of Heptio Kubernetes solutions and tooling at external meet ups and tech exchanges
 - title: PreSales Specialist System Engineer
   start: 2016
   end: 2018
   employer: RedHat
   description: RedHat is the world's leading provider of enterprise open source solutions, including high-performing Linux, cloud, container, and Kubernetes technologies. <br/> Working as a PreSales technical specialist, I worked closely with the Sales teams to perform technical demonstrations and on-site PoCs around Automation - CloudForms, Ansible, Openshift, docker, Kubernetes, Cloud Management, Cloud provisioning;  I was also involved in the evangelism of Red Hat solutions, products and culture at external meet ups, tech-exchanges and roadshows.
 - title: Lead Architect
   start: 2006
   end: 2016
   employer: HP and Fujitsu
   description: This role was as a contractor for a consortium of HP and Fujitsu to modernise a large defence-based organisation. <br/> Working in various roles leading to lead arhcitect we implemented some significant milestones including;  successful daily management of 200K endpoints (desktops, servers, users) for OS and application deployment, patching, hardening, and reporting; design and implementation of first virtualised environments with automated self service provisioning; developed RESTful API driven content synchronisation system that improved time-to-sync and operational times by 50pc. <br/> As Lead Architect, I was the technical authority on enterprise management for all high profile customer engagements.  
 - title: Global Desktop Manager
   start: 2005
   end: 2006
   employer: Clifford Chance
   description: In this role, I was Manager of Desktop functions within 20 teams across 5 global regions. <br/> Here I worked on streamlining the content distribution solution; developed a global reporting reporting solution for security patch delivery; the introduction of virtualised test beds for all OS, patch and application testing; ran global and regional team technical briefs; ran internal customer solution updates and assurance

#Education is required
education:
 - level: Bachelor of Science - (B.Sc.)
   date: 1993
   subject: Industrial Biochemistry - First Class
   school: University of Limerick
   
 - level: Doctorate of Philosophy (Ph.D)
   date: 2003
   subject: Oncology - Distinction Class
   school: University College London

additionalinfo: |
   I am involved in several initiative to help drive the education and adoption of cloud native principles and technologies.<br/> This includes being part of external trainings platform, podcasts and external meetups.<br/> My major contributions are as follows:<br/><br/>
   <strong><font color="green">Education</font color></strong><br/>
   <a target="_blank" href="https://kube.academy/"><strong>Kube-Academy</strong></a>: A free online Kubernetes training portal for which I am a resident instructor<br/><br/>
   <a target="_blank" href="https://connect.tanzu.vmware.com/KubeAcademy-Tour-APJ.html"><strong>KubeAcademy APJ Tour</strong></a>: A Series of free training on Containers and Kubernetes to be delivered in APJ over the next 4 months, at which I will be the main presenter <br/><br/>

   <strong><font color="green">Podcasts</font color></strong><br/>
   <a target="_blank" href="https://thepodlets.io/"><strong>The Podlets</strong></a>: A podcast that discusses topical cloud native subjects and concepts<br/><br/>

   <strong><font color="green">Conferances and Meetups</font color></strong><br/>
   <a target="_blank" href="https://www.youtube.com/watch?v=faVXF52u0_s"><strong>KubeCon EU 2019</strong></a>: Ready, Steady, CKA!  - A lightening talk on how to pass the CKA exam<br/>
   <a target="_blank" href="https://www.youtube.com/watch?v=8JFRw9dZU_s"><strong>Kubernetes Summit Sydney/Seoul</strong></a>: Smooth Operator - A Rough Guide to Kubernetes Operators<br/>
   <a target="_blank" href="https://www.youtube.com/watch?v=ML8rfSOi2n0"><strong>DevOps Exchange, London</strong></a>: Open Source tooling for taming your Kubernetes wild horses<br/>
   <a target="_blank" href="https://www.meetup.com/Singapore-Kubernetes-User-Group/events/268492981/"><strong>Singapore Kubernetes User Group</strong></a>: This is one of many worldwide groups set up to build a community tha is interested Kubernetes and other cloud native technologies, of which I am a contributor and host<br/>


#This section is optional (as is the image link below)
coursera:
    profileurl: https://www.google.com
    courses:
     - title: Certified Kubernetes Administrator
       link: https://www.cncf.io/certification/cka/
       optionalimage: https://miro.medium.com/max/840/1*gl0UTVp45-TpCXnIWo5gQQ.png
       date: May, 2019
     - title: Certified Kubernetes Administrator - Developer
       link: https://www.cncf.io/certification/ckad/
       optionalimage: https://miro.medium.com/max/840/1*gl0UTVp45-TpCXnIWo5gQQ.png
       date: May, 2019
     - title: Red Hat Certified Engineer
       link: https://www.redhat.com/en/services/certification/rhce
       optionalimage: https://www.whizlabs.com/blog/wp-content/uploads/2019/02/rhce-preparation-guide.png
       date: May, 2017
     - title: Red Hat Certified in Automation with Ansible
       link: https://www.redhat.com/en/services/certification/rhcs-ansible-automation
       optionalimage: https://encrypted-tbn0.gstatic.com/images?#q=tbn%3AANd9GcRZzN4YfxzuXh6uATWhmXHAEJ6917ocAzWNKg&usqp=CAU
       date: May, 2018
   
intro: |
  I am a motivated IT Professional with 19+ years industry experience, covering Enterprise Management, Containers, Kubernetes, Cloud and Virtualisation, Desired state, Automation, DevOps, Security and Compliance, Linux and Wintel.<br/> I possess excellent communication and organisational skills and work well in a team or isolation. <br/>I have engaged with C-level executives for design reviews, strategic direction, assurance briefs and product updates and can relate effectively to technical and sales teams across a broad range of disciplines. <br/> I am a dynamic person with a flexible, focused and professional approach to work.<br/> I seek a position that will provide new learning and networking opportunities, responsibilities and intellectual challenges. <br/>
  I am currently working as an Emerging Technology Solution Solution Engineer, for VMware in the APJ region, having moved over from Heptio.<br/>
   
